Fix Dockerfile and bash scripts
extremeprog-com/mongo-sites-api pull request #18
Opened 2016-12-12 18:09 UTC by dmitrykuzmenkov

2016-12-12 19:36 UTC, myfoxtail approved these changes

2016-12-15 08:52 UTC, okneigres requested changes

2016-12-15 08:52 UTC, okneigres commented on Dockerfile
> +ENTRYPOINT ["bash", "/root/mongo-sites-api/run_app.sh"]
Don't agree with that. It can be inconvenient in many cases. For example if we want to build volume container based on that or customize behaviour.

2016-12-15 08:52 UTC, okneigres commented on pack/Dockerfile
> +ENTRYPOINT ["bash", "/root/mongo-sites-api/run_app.sh"]
Same as in comment above.

2016-12-21 13:48 UTC, okneigres approved these changes

2016-12-21 13:52 UTC, merged